import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Rahandi Noor Pasha
        </h1>

        <p className={styles.description}>
          <p>
            <a href="mailto:rahandinoor@gmail.com">rahandinoor@gmail.com</a>
            <br></br>
            <a href="https://linkedin.com/in/rahandi">linkedin.com/in/rahandi</a>
            <br></br>
            <a href="https://github.com/Rahandi>">github.com/Rahandi</a>
          </p>
        </p>

        <div className={styles.grid}>
          <div className={styles.section}>
            <h2>Experience</h2>
            <p className={styles.card}>
              <h3>Software Development Engineer in Test</h3>
              <h5>Traveloka, Indonesia, November 2021 - Present</h5>
              abc
            </p>
            <p className={styles.card}>
              <h3>Devops Engineer</h3>
              <h5>Prixa.ai, Indonesia, May 2021 - November 2021</h5>
              acbasca
            </p>
            <p className={styles.card}>
              <h3>Software Engineer</h3>
              <h5>Prixa.ai, Indonesia, March 2020 - May 2021</h5>
              abc
            </p>
          </div>
          <div className={styles.section}>
            <h2>Skills</h2>
            <p className={styles.card}>
              <div>
                <h3>Languages</h3>
                <table>
                  <thead>
                    <tr>
                      <th>Experienced</th>
                      <th>Familiar</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Typescript</td>
                      <td>HTML</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        blablabla
      </footer>
    </div>
  )
}

export default Home
